GET http://localhost:3003/

###
GET http://localhost:3003/hello

###
GET http://localhost:3003/bmi?height=400&weight=3300

###
POST http://localhost:3003/calculate
Content-Type: application/json

{
    "value1": 10,
    "value2": 20,
    "op": "add"
}

###
POST http://localhost:3003/exercises
Content-Type: application/json

{
 "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}


